# Generated by Django 2.0.13 on 2019-11-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191107_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
