# Generated by Django 2.0.13 on 2019-11-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191107_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Categories'),
        ),
        migrations.AddField(
            model_name='categories',
            name='catalog',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.Catalog'),
        ),
    ]
