# Generated by Django 2.0.13 on 2019-11-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191107_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.Categories'),
        ),
    ]
