# Generated by Django 2.0.13 on 2019-11-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191107_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='catalog',
        ),
        migrations.AddField(
            model_name='catalog',
            name='categories',
            field=models.ForeignKey(default='1', on_delete=None, to='shop.Categories'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='number',
            field=models.IntegerField(default='1'),
        ),
    ]
