# Generated by Django 2.0.13 on 2019-11-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191107_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='categories',
        ),
        migrations.AddField(
            model_name='catalog',
            name='categories',
            field=models.ManyToManyField(related_name='catalogs', to='shop.Categories'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='number',
            field=models.IntegerField(),
        ),
    ]
