# Generated by Django 2.0.13 on 2019-11-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191107_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='categories',
        ),
        migrations.AddField(
            model_name='categories',
            name='catalog',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.Catalog'),
        ),
    ]
