# Generated by Django 2.0.13 on 2019-11-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20191108_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='short_name',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(default='1', max_length=15),
        ),
    ]
