# Generated by Django 2.1.1 on 2019-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20191108_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
