# Generated by Django 2.1.1 on 2019-11-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
