# Generated by Django 2.1.1 on 2019-11-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20191114_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
